config/routes.rb
Rails.application.routes.draw do

  get 'customers/alphabetized' => 'finder#alphabetized'

  get 'customers/missing_email' => 'finder#missing_email'

  get 'customers' => 'finder#index'

  root to: 'finder#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :phone_number, presence: true
  belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where("email_address == ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.slim
.customer
	h3 = customer.full_name
	= image_tag customer.image
	
	- if customer.province.blank?
		p 
			b Province: 
			| None
	- else
		p
			b Province: 
			= customer.province.name

	p
		b Phone: 
		= customer.phone_number
		
	- unless customer.email_address.blank?
		p
			b Email: 
			= customer.email_address

	- unless customer.notes.blank?
	p
		b Notes: 
		= customer.notes

app/views/finder/alphabetized.html.slim
h2 Alphabetized Customers
= render @customers

app/views/finder/index.html.slim
h2 All Customers
= render @customers

app/views/finder/missing_email.html.slim
h2 Missing Email Customers
= render @customers

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeSeven</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="wrapper">
	  	<h1>Customer Relation Manager</h1>
	  	<nav>
	  		<ul>
	  			<li><%= link_to 'All Customers', customers_path %></li>
	  			<li><%= link_to 'Alphabetized Customers', customers_alphabetized_path %></li>
	  			<li><%= link_to 'Missing Email Customers', customers_missing_email_path %></li>
	  		</ul>
	  	</nav>
	  	
	    <%= yield %>
    </div>
  </body>
</html>